packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Core Framework
  react: ^19.2.0
  react-dom: ^19.2.0
  next: 15.5.4

  # TypeScript & Build Tools
  typescript: ^5.4.5
  tsx: ^4.20.3
  esbuild: 0.23.0

  # Monorepo & Build
  turbo: ^2.4.2
  rimraf: ^6.0.1

  # Code Quality
  prettier: ^3.3.3
  eslint: 8.57.0
  "eslint-config-next": 15.5.4
  "eslint-config-turbo": ^2.0.0
  "eslint-config-prettier": ^9.1.0
  "eslint-plugin-prettier": ^5.2.1
  "eslint-plugin-only-warn": ^1.1.0
  "@typescript-eslint/parser": ^7.1.0
  "@typescript-eslint/eslint-plugin": ^7.1.0
  "@vercel/style-guide": ^5.2.0

  # Git Hooks
  husky: ^9.1.4
  "lint-staged": ^16.1.5
  "@commitlint/cli": ^19.3.0
  "@commitlint/config-conventional": ^19.2.2

  # Node Types
  "@types/node": ^20
  "@types/react": ^18
  "@types/react-dom": ^18

  # Testing
  vitest: ^3.0.0
  "@vitest/ui": ^3.0.0
  "@vitejs/plugin-react": ^4.3.4
  "@testing-library/react": ^16.0.0
  "@testing-library/jest-dom": ^6.5.0
  "@testing-library/user-event": ^14.5.2
  happy-dom: ^15.11.7
